### ISSUE TITLE
qcef need files from private repo

### ISSUE THREAD

**Issue by sztsian** [linuxdeepin/qcef#3]
> $ git submodule update --init --recursive
> Submodule 'cef' (https://cr.deepin.io/cef-binary) registered for path 'cef'
> Cloning into '/tmp/qcef/cef'

As this requires file from private repo, I believe this repo is not essentially to be a public repo.

**Comment by felixonmars** [comment]
The cef-binary repo was mirrored at https://github.com/linuxdeepin/cef-binary though.

**Comment by sztsian** [comment]
Thanks... So can you add this to README ? Then you can close this ticket as resolved.

**Comment by felixonmars** [comment]
I'll double confirm this with the developer before that. Thanks for bringing this up :)

**Comment by felixonmars** [comment]
Confirmed and made the gerrit project open as well.
